### ISSUE TITLE
测试librispeech的问题 

### ISSUE THREAD

**Issue by feina1** [lingochamp/kaldi-ctc#10]
运行run.sh时, 在stage=-2时卡住:
local/data_prep.sh $data/LibriSpeech/$part data/$(echo $part | sed s/-/_/g) 
追进去, 是在这一步卡住:
utils/data/get_utt2dur.sh $dst 1>&2 || exit 1
在eeesen的data_prep.sh里面, 好像这一步不存在
系统提示:
utils/data/get_utt2dur.sh: segments file does not exist so getting durations from wave files
utils/data/get_utt2dur.sh: could not get utterance lengths from sphere-file headers, using wav-to-duration
utils/data/get_utt2dur.sh: wav-to-duration is not on your path

请问如何解决? 谢谢!

**Comment by lifeiteng** [comment]
`utils/data/get_utt2dur.sh: wav-to-duration is not on your path`

**Comment by feina1** [comment]
那怎样解决呢? 不好意思
