### ISSUE TITLE
I got a 'ctcComputeInfo' not declared error when i complie kaldi-ctc.

### ISSUE THREAD

**Issue by tratotasia** [lingochamp/kaldi-ctc#3]
ctc-nnet-update.cc: In member function ‘bool kaldi::ctc::NnetCtcUpdater::ComputeObjfAndDeriv(const std::vector<kaldi::ctc::NnetCtcExample>&, kaldi::CuMatrix<float>*, double*, double*) const’:
ctc-nnet-update.cc:200:3: error: ‘ctcComputeInfo’ was not declared in this scope
   ctcComputeInfo info;
   ^
ctc-nnet-update.cc:201:3: error: ‘info’ was not declared in this scope
   info.loc = CTC_GPU;
   ^
In file included from ../base/kaldi-common.h:38:0,
                 from ../util/stl-utils.h:45,
                 from ../util/edit-distance-inl.h:25,
                 from ../util/edit-distance.h:29,
                 from ctc-nnet-update.cc:24:

any one got the same erorr? i grep the whole kaldi-ctc project including tools, nothing was found about ctcComputeInfo.

am i missing any dependant library? or i complied in a wrong way?

**Comment by lifeiteng** [comment]
install warpctc `tools/extras/install_warp_ctc.sh`

**Comment by tratotasia** [comment]
I've done that before, it's helpless, would you please tell me which file the ctcComputeInfo class is located? I just can't find this class anywhere.

**Comment by tratotasia** [comment]
warp-ctc has change the parameter from ctcComputeInfo to ctcOption in function get_workspace_size. 
change the the code in ctc-nnet-update.cc:200 as below:

ctcComputeInfo info ..........change to  ctcOption info

that will solve the problem, i think the master branch should be updated too. @lifeiteng 

thanks.

**Comment by tratotasia** [comment]
I run thchs30 example using kaldi-ctc, when going to the steps/ctc/train.sh step, it failed with the following error.

ERROR (nnet2-ctc-train-simple:ComputeObjfAndDeriv():ctc-nnet-update.cc:224) ctcStatus_t 1 : "cuda memcpy or memset failed" returned from 'compute_ctc_loss(output.Data(), deriv->Data(), flat_labels.data(), label_lengths.data(), input_lengths.data(), alphabet_size, mini_batch, costs.Data(), ctc_gpu_workspace, info)'

[ Stack-Trace: ]
ERROR (nnet2-ctc-train-simple:ComputeObjfAndDeriv():ctc-nnet-update.cc:224) ctcStatus_t 1 : "cuda memcpy or memset failed" returned from 'compute_ctc_loss(output.Data(), deriv->Data(), flat_labels.data(), label_lengths.data(), input_lengths.data(), alphabet_size, mini_batch, costs.Data(), ctc_gpu_workspace, info)'


tracing that error location, it seems changing ctcComputeInfo to ctcOption in the source file ctc-nnet-update.cc i memtioned above is wrong, maybe it's the reason of the error.


back to this issue, how to fix the original question and the new on?


PS:
would you please tell me which file the ctcComputeInfo class is located? I just can't find this class anywhere. @lifeiteng 


MANY THANKS

**Comment by lifeiteng** [comment]
@tratotasia  There's a new varible `    int blank_label;` in `ctcOption`, I've tried fix this https://github.com/lingochamp/kaldi-ctc/commit/b3e24a6e1e53683a44ff23ed27c2f1dcac1e1da9,
but not test it yet.

**Comment by tratotasia** [comment]
@lifeiteng it works
