### ISSUE TITLE
compile error in nnet2 when dealing with nnet-nnet.cc

### ISSUE THREAD

**Issue by Diamondfan** [lingochamp/kaldi-ctc#5]
When I do "make -j 4" in kaldi-ctc/src. It occurs some errors.
The error is:
nnet-nnet.cc: In member function ‘void kaldi::nnet2::Nnet::SetMiniBatch(int32) const’:
nnet-nnet.cc:47:20: error: ‘CuDNNRecurrentComponent’ does not name a type
       dynamic_cast<CuDNNRecurrentComponent *>(components_[i])->InitMiniBatch(m
                    ^
nnet-nnet.cc:47:44: error: expected ‘>’ before ‘*’ token
       dynamic_cast<CuDNNRecurrentComponent *>(components_[i])->InitMiniBatch(m
                                            ^
nnet-nnet.cc:47:44: error: expected ‘(’ before ‘*’ token
nnet-nnet.cc:47:45: error: expected primary-expression before ‘>’ token
       dynamic_cast<CuDNNRecurrentComponent *>(components_[i])->InitMiniBatch(m
                                             ^
nnet-nnet.cc:47:64: error: ‘class kaldi::nnet2::Component’ has no member named ‘InitMiniBatch’
       dynamic_cast<CuDNNRecurrentComponent *>(components_[i])->InitMiniBatch(m
 
The code in nnet-nnet.cc:47 is:
void Nnet::SetMiniBatch(int32 mini_batch) const {
  KALDI_ASSERT(!components_.empty());
  KALDI_ASSERT(mini_batch > 0);
  for (size_t i = 0; i < components_.size(); i++) {
    if (components_[i]->Type() == "CuDNNRecurrentComponent") {
      dynamic_cast<CuDNNRecurrentComponent *>(components_[i])->InitMiniBatch(mini_batch, 0);
    }
  }
}
The reason is that CudnnRecurrentcomponent is not a type.But it includes the nnet-cudnn-componnet.h which declar this type. I don't know how to solve it. Is it a problem of my computer?

**Comment by lifeiteng** [comment]
make sure `cudnn(>=5.0)` is installed.

**Comment by Diamondfan** [comment]
I'm sure I have installed the cudnn8.0 V5.1. And I just updated it to V6.0,but it doesn't help. I can use cuda and cudnn with tensorflow. I have spent a whole day on it.

**Comment by lifeiteng** [comment]
check `src/kaldi.mk` (generated by `./configure --cudnn-root=YOUR_CUDNN_ROOT --openblas-root=../tools/OpenBLAS/install`), it should have `-DHAVE_CUDNN=1 -DHAVE_CUDA=1`;
if not, please read https://github.com/lingochamp/kaldi-ctc#compilation

**Comment by Diamondfan** [comment]
The problem solved. I read the INSTALL file to compile as the old way in kaldi. I suggest changing the INSTALL file in the dir tools and src. Maybe I'm too careless. And I found that when using cudnn8 V6.0, it also get errors. And I returned to V5.1. It works well. At last, thanks for help.

**Comment by lifeiteng** [comment]
different cudnn versions vary widely.
tools/extras/install_cuda.sh installs cuda v5.1.
