### ISSUE TITLE
error in wav-to-duration

### ISSUE THREAD

**Issue by kishaly** [lingochamp/kaldi-ctc#6]
Hello I have installed kaldi-ctc according to instruction given. 
while testing the system with librispeech  using "bash run.sh --stage -2 --num-gpus 4"
it is showing some error 

utils/data/get_utt2dur.sh: segments file does not exist so getting durations from wave files
utils/data/get_utt2dur.sh: could not get utterance lengths from sphere-file headers, using wav-to-duration
utils/data/get_utt2dur.sh: wav-to-duration is not on your path

How to solve the problem?

**Comment by lifeiteng** [comment]
add kaldi-ctc/src/featbin into PATH.

**Comment by ktheadmin** [comment]
thank you

**Comment by gwyanCN** [comment]
Hello, I have tried add the path of featbin into PATH. However,  there is a error of "wav-to-duration: command not found".
