### ISSUE TITLE
online decoding for ctc

### ISSUE THREAD

**Issue by upsDreamer** [lingochamp/kaldi-ctc#8]
I use 
../latbin/lattice-1best --lm-scale=5 "ark:gunzip -c $indir/lat.JOB.gz|" ark:tmp
../latbin/lattice-align-words-lexicon $wbfile $mdl ark:tmp ark:tmp1
../latbin/nbest-to-ctm --frame-shift=0.01 --print-silence=true ark:tmp1 $out_dir/$out_name.txt 
I want to get every words time information, but I got some problem.

Is there any online decoding examples like kaldi online2bin/online2-wav-nnet2-latgen-faster ?
Which script can I learn from ?

thank you

**Comment by lifeiteng** [comment]
No.
